"""Add Steam integration

Revision ID: 768bce57ed0a
Revises: 5519faf93ac6
Create Date: 2025-11-09 15:03:57.672607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768bce57ed0a'
down_revision: Union[str, Sequence[str], None] = '5519faf93ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Game', sa.Column('steam_id', sa.Integer(), nullable=True))
    op.add_column('Game', sa.Column('steam_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Game', 'steam_url')
    op.drop_column('Game', 'steam_id')
    # ### end Alembic commands ###
