"""Add faves

Revision ID: b1820e1947b5
Revises: 
Create Date: 2020-07-05 16:58:27.304927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1820e1947b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Play', sa.Column('fave', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Play', 'fave')
    # ### end Alembic commands ###
