"""Add local image storage

Revision ID: c910d6963cf3
Revises: 92f7d0653a09
Create Date: 2021-12-29 15:16:04.110799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c910d6963cf3'
down_revision = '92f7d0653a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Game', sa.Column('image_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Game', 'image_file')
    # ### end Alembic commands ###
